#pragma once
#include <Arduino.h>
#include <Arduino_GFX_Library.h>
#include "japanese_font_atlas.h"
#include "japanese_large_font_atlas.h"
namespace JapaneseUI {
static const uint8_t kBodyLineHeight=20, kButtonLineHeight=20;
inline size_t nextCodepoint(const char*s,size_t o){uint8_t a=s[o];if(!a)return o;size_t n=(a<128)?1:((a&224)==192)?2:((a&240)==224)?3:((a&248)==240)?4:1;for(size_t i=1;i<n;i++){uint8_t c=s[o+i];if(!c||(c&192)!=128)return o+1;}return o+n;}
inline uint32_t decode(const char*s,size_t p,size_t e){uint8_t a=s[p];if(a<128)return a;if((a&224)==192&&p+1<e)return((a&31)<<6)|(s[p+1]&63);if((a&240)==224&&p+2<e)return((a&15)<<12)|((s[p+1]&63)<<6)|(s[p+2]&63);if((a&248)==240&&p+3<e)return((a&7)<<18)|((s[p+1]&63)<<12)|((s[p+2]&63)<<6)|(s[p+3]&63);return '?';}
inline uint16_t blend565(uint16_t f,uint16_t b,uint8_t a,uint8_t levels=3){if(a==0)return b;if(a>=levels)return f;uint16_t fr=(f>>11)&31,fg=(f>>5)&63,fb=f&31,br=(b>>11)&31,bg=(b>>5)&63,bb=b&31;return((fr*a+br*(levels-a))/levels<<11)|((fg*a+bg*(levels-a))/levels<<5)|((fb*a+bb*(levels-a))/levels);}
inline void selectFont(Arduino_GFX*g,bool l){(void)g;(void)l;}
inline const JapaneseFontGlyph* glyph(uint32_t cp){size_t l=0,h=japanese_font_glyph_count;while(l<h){size_t m=(l+h)/2;if(japanese_font_glyphs[m].codepoint<cp)l=m+1;else h=m;}if(l<japanese_font_glyph_count&&japanese_font_glyphs[l].codepoint==cp)return&japanese_font_glyphs[l];l=0;h=japanese_font_glyph_count;while(l<h){size_t m=(l+h)/2;if(japanese_font_glyphs[m].codepoint<63)l=m+1;else h=m;}return&japanese_font_glyphs[l];}
inline const JapaneseLargeFontGlyph* largeGlyph(uint32_t cp);
inline uint16_t pixelWidth(Arduino_GFX*g,const String&t,bool large=false){(void)g;uint16_t w=0;size_t p=0;while(p<t.length()){size_t n=nextCodepoint(t.c_str(),p);uint32_t cp=decode(t.c_str(),p,n);const JapaneseLargeFontGlyph*lq=large?largeGlyph(cp):nullptr;uint8_t advance=glyph(cp)->advance;w+=lq?lq->advance:(large?((uint16_t(advance)*20+8)/16):advance);p=n;}return w;}
inline int16_t baselineForTop(Arduino_GFX*g,int16_t t){(void)g;return t+14;}
inline uint8_t atlasAlpha(const JapaneseFontGlyph*q,int16_t x,int16_t y){x-=q->xOffset;y-=q->yOffset;if(x<0||x>=q->width||y<0||y>=q->height)return 0;uint16_t i=y*q->width+x;uint8_t v=pgm_read_byte(q->bitmap+(i>>2));return(v>>((3-(i&3))*2))&3;}
inline const JapaneseLargeFontGlyph* largeGlyph(uint32_t cp){size_t l=0,h=japanese_large_font_glyph_count;while(l<h){size_t m=(l+h)/2;uint32_t candidate=japanese_large_font_glyphs[m].codepoint;if(candidate<cp)l=m+1;else h=m;}return l<japanese_large_font_glyph_count&&japanese_large_font_glyphs[l].codepoint==cp?&japanese_large_font_glyphs[l]:0;}
inline uint8_t largeAtlasAlpha(const JapaneseLargeFontGlyph*q,int16_t x,int16_t y){x-=q->xOffset;y-=q->yOffset;if(x<0||x>=q->width||y<0||y>=q->height)return 0;uint16_t i=y*q->width+x;uint8_t v=pgm_read_byte(q->bitmap+(i>>1));return(v>>((1-(i&1))*4))&15;}
inline int16_t scaleFloor(int16_t v){return v>=0?v*5/4:-((-v*5+3)/4);}
inline int16_t scaleCeil(int16_t v){return v>=0?(v*5+3)/4:-((-v*5)/4);}
inline uint8_t scaledAlpha(const JapaneseFontGlyph*q,int16_t x,int16_t y){// Keep the body baseline at 14 mapped to the native 20px baseline at 18.
int32_t sx=int32_t(x)*256*4/5,sy=int32_t(y-18)*256*4/5+14*256;int16_t x0=sx>=0?sx/256:-((-sx+255)/256),y0=sy>=0?sy/256:-((-sy+255)/256);uint16_t fx=sx-int32_t(x0)*256,fy=sy-int32_t(y0)*256;uint16_t a00=atlasAlpha(q,x0,y0),a10=atlasAlpha(q,x0+1,y0),a01=atlasAlpha(q,x0,y0+1),a11=atlasAlpha(q,x0+1,y0+1);uint32_t top=uint32_t(a00)*(256-fx)+uint32_t(a10)*fx,bottom=uint32_t(a01)*(256-fx)+uint32_t(a11)*fx;return(uint8_t)((top*(256-fy)+bottom*fy+32768)>>16);}
inline void draw(Arduino_GFX*g,const String&t,int16_t x,int16_t top,uint16_t color,bool large=false,uint16_t background=0x10C4){if(!g)return;Arduino_Canvas*canvas=static_cast<Arduino_Canvas*>(g);uint16_t*fb=canvas->getFramebuffer();int16_t pen=x;size_t p=0;while(p<t.length()){size_t n=nextCodepoint(t.c_str(),p);uint32_t cp=decode(t.c_str(),p,n);const JapaneseFontGlyph*q=glyph(cp);const JapaneseLargeFontGlyph*lq=large?largeGlyph(cp):nullptr;int16_t left=lq?lq->xOffset:(large?scaleFloor(q->xOffset-1):q->xOffset),startY=lq?lq->yOffset:(large?18+scaleFloor(q->yOffset-14-1):q->yOffset);uint8_t width=lq?lq->width:(large?scaleCeil(q->xOffset+q->width)-left:q->width),height=lq?lq->height:(large?18+scaleCeil(q->yOffset+q->height-14)-startY:q->height);for(int16_t yy=startY;yy<startY+height;yy++)for(int16_t xx=left;xx<left+width;xx++){int16_t dx=pen+xx,dy=top+yy;if(dx<0||dy<0||dx>=g->width()||dy>=g->height())continue;uint8_t a=lq?largeAtlasAlpha(lq,xx,yy):(large?scaledAlpha(q,xx,yy):atlasAlpha(q,xx,yy));if(a){uint16_t bg=fb?fb[dy*g->width()+dx]:background;g->drawPixel(dx,dy,blend565(color,bg,a,lq?15:3));}}pen+=lq?lq->advance:(large?((uint16_t(q->advance)*20+8)/16):q->advance);p=n;}}
inline String printable(String t){return t;}
inline String ellipsize(Arduino_GFX*g,const String&t,uint16_t w){static const String e="...";if(pixelWidth(g,t)<=w)return t;String o;size_t p=0;while(p<t.length()){size_t n=nextCodepoint(t.c_str(),p);String c=t.substring(p,n);if(pixelWidth(g,o+c+e)>w)break;o+=c;p=n;}return o+e;}
inline uint8_t wrapped(Arduino_GFX*g,const String&t,int16_t x,int16_t top,uint16_t w,uint8_t ml,uint16_t color,uint8_t lh=kBodyLineHeight){if(!g||!ml||!w)return 0;uint8_t line=0;size_t p=0;String cur;while(line<ml){if(p>=t.length()&&!cur.length())break;while(p<t.length()){if(t[p]=='\n'){p++;break;}size_t n=nextCodepoint(t.c_str(),p);String c=t.substring(p,n);if(pixelWidth(g,cur+c)>w&&cur.length())break;cur+=c;p=n;if(pixelWidth(g,cur)>w)break;}bool more=p<t.length();String shown=cur;if(line+1==ml&&more){static const String suffix="...";while(shown.length()&&pixelWidth(g,shown+suffix)>w){size_t e=shown.length(),b=0;while(b<e){size_t n=nextCodepoint(shown.c_str(),b);if(n>=e)break;b=n;}shown.remove(b);}shown+=suffix;}draw(g,shown,x,top+line*lh,color);line++;cur="";if(p>=t.length())break;}return line;}
}
